### ISSUE TITLE
Plugin hook uses a ref to barcode value

### ISSUE THREAD

**Issue by fridobox** [bywatersolutions/koha-plugin-barcode-transformer#5]
Hi,

Since the hook is called in a recursive mode, the barcode is transmitted as a ref to value.
 
See for example the test suite :
https://git.koha-community.org/Koha-community/Koha/src/commit/a6ef152db9e71805efe8e7dd6b2f8549da0f65b4/t/lib/plugins/Koha/Plugin/TestItemBarcodeTransform.pm#L35

Plus, no need to return changed value.

Best regards,

**Comment by kylemhall** [comment]
Thanks @fridobox! This should be fixed now!
